version: "3.7"
services:
  database:
    image: mysql:8.0
    env_file:
      - ./DB/.env
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    restart: on-failure
    volumes:
      - db_search_enginge:/var/lib/mysql
    ports:
      - "3306:3306"
    command: "--ngram_token_size=4 --innodb_ft_enable_stopword=off"

  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - database

volumes:
  db_search_enginge: