FROM python:3.9-slim-buster

RUN apt-get update

# install build tools
RUN apt-get install -y build-essential
RUN apt-get install -y python3-numpy libicu-dev python3-icu
RUN apt-get install -y libmariadb3 libmariadb-dev

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

WORKDIR /app/website

ENTRYPOINT ["streamlit", "run", "main.py"]