version: "3.7"
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile_spider
    env_file:
      - ./DB/.env
      - ./scraper/.env
    networks:
      - db_search_enginge
    volumes:
      - .:/app

networks:
  db_search_enginge: