version: "3.7"
services:
  website:
    build:
      context: .
      dockerfile: ./Dockerfile_website
    volumes:
      - ./website:/app/website
      - ./DB:/app/DB
    env_file:
      - ./DB/.env
    network_mode: host