version: "3.7"
services:
  website:
    build:
      context: .
      dockerfile: ./Dockerfile_website
    volumes:
      - ./website:/app/website
      - ./DB:/app/DB
    env_file:
      - ./DB/.env
    networks:
      - db_search_enginge
    ports:
      - "8501:8501"
    command: ["--browser.serverAddress", "localhost"]

networks:
  db_search_enginge: