version: "3.7"
services:
  mariadb:
    image: mysql:8.0
    env_file:
      - ./DB/.env
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    restart: on-failure
    #volumes:
      #- mariadb_db_search_enginge:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mariadb

# volumes:
#   mariadb_db_search_enginge: