FROM python:3.9-slim-buster

WORKDIR /app

RUN apt-get update

# install build tools
RUN apt-get install -y build-essential
RUN apt-get install -y python3-numpy libicu-dev python3-icu

COPY requirements_spider.txt .

RUN pip install -r requirements_spider.txt

RUN python -m spacy download en_core_web_sm
RUN python -m spacy download de_core_news_sm

WORKDIR /app/scraper
CMD ["python", "spider.py"]