FROM python:3.9-slim-buster

RUN apt-get update

# install build tools
RUN apt-get install -y build-essential

WORKDIR /app

COPY requirements_website.txt .

RUN pip install -r requirements_website.txt

WORKDIR /app/website

ENTRYPOINT ["streamlit", "run", "main.py"]